### ISSUE TITLE
[docs] Reproducible Runtime

### ISSUE THREAD

**Issue by brandtkeller** [Credentive-Sec/metaschema-codegen#1]
# Description

Request for documentation to support running representative or current workflow for code generation. 

Making some assumptions currently as to what the pre-requisites are to running a test that produces the current python datatypes.  Objective being that I can begin thinking about what an additional golang workflow would entail. 

Things like:
- git submodules
- python virtual environment + poetry installation + ...
- Ability to run tests and/or imperative workflows (command execution etc)

I'm far from an expert in python and developer tooling. Comments here or in updated docs would be appreciated.

**Comment by RS-Credentive** [comment]
Good, catch Brandt. I need to validate my assumptions about how this will work on a new environment, and I will update documentation. I use vscode w/ the pyenv poetry devcontainer as the base, but I've usually had to tweak when I rebuild so let me fix what I can and document all of the little build dependencies that are left. I will add another comment when it's done. Couple of days.

**Comment by brandtkeller** [comment]
Much appreciated! I made my way through a variety of steps towards setting up a development environment but I wanted to iron out the reproducible piece such that I can ensure what you see as outputs is the same as what I see. 

Common baseline if you will.

**Comment by RS-Credentive** [comment]
Brandt, I've made some updates to the dev environment, and created a README (on the dev branch) that should produce a very consistent environment. I've also documented some of the tricks I use to inspect the data by running tests in debug mode with breakpoints. It would probably be best to tear everything down and rebuild from scratch rather than trying to migrate from the current dev environment to the new one. Please let me know if you are still having trouble getting your environment set up.
